// AUTOGENERATED BY @mikechau/js-config-gen.

'use strict';

var _ = require('lodash');

var webpack = require('webpack');
var baseWebpackConfig = require('./node_modules/@mikechau/js-config-gen/dist/react-web/base-webpack.config.test');

var config = _.merge({}, baseWebpackConfig, {
  /**
   * Loaders
   *
   * https://webpack.github.io/docs/loaders.html
   *
   * Loaders match for a particular file extension, options to the loader are provided by query param
   *
   * Style Loader: https://github.com/webpack/style-loader
   * CSS Loader: https://github.com/webpack/css-loader
   * LESS Loader: https://github.com/webpack/less-loader
   * SASS Loader: https://github.com/jtangelder/sass-loader
   *
   * Development/Test builds do not need the ExtractTextPlugin.
   * Leaves styles inline.
   *
   */
  module: {
    loaders: baseWebpackConfig.module.loaders.concat([
      {
        'test': /\.css$/,
        'loader': 'style!css'
      },
      {
        'test': /\.less$/,
        'loader': 'style!css!less'
      },
      {
        'test': /\.scss$/,
        'loader': 'style!css!scss'
      }
    ])
  },

  plugins: [
    /**
     * Define Plugin
     *
     * https://webpack.github.io/docs/list-of-plugins.html#defineplugin
     *
     * Defines global constants, we define NODE_ENV to enable React production
     * mode
     *
     * https://facebook.github.io/react/downloads.html#npm
     *
     */
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'test')
      }
    }),

    /**
     * No Errors Plugin
     *
     * https://webpack.github.io/docs/list-of-plugins.html#noerrorsplugin
     *
     * No assets are emitted when there are build errors.
     *
     */
    new webpack.NoErrorsPlugin()
  ]
});

module.exports = config;
